(function() {var implementors = {};
implementors["tower_grpc"] = [{text:"impl&lt;T, U&gt; <a class=\"trait\" href=\"tower_grpc/codegen/client/tower_h2/trait.Body.html\" title=\"trait tower_grpc::codegen::client::tower_h2::Body\">Body</a> for <a class=\"struct\" href=\"tower_grpc/generic/struct.Encode.html\" title=\"struct tower_grpc::generic::Encode\">Encode</a>&lt;T, U&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"tower_grpc/generic/trait.Encoder.html\" title=\"trait tower_grpc::generic::Encoder\">Encoder</a>&lt;Item = U::<a class=\"type\" href=\"tower_grpc/codegen/server/futures/trait.Stream.html#associatedtype.Item\" title=\"type tower_grpc::codegen::server::futures::Stream::Item\">Item</a>&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;U: <a class=\"trait\" href=\"tower_grpc/codegen/server/futures/trait.Stream.html\" title=\"trait tower_grpc::codegen::server::futures::Stream\">Stream</a>,&nbsp;</span>",synthetic:false,types:["tower_grpc::generic::codec::Encode"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"tower_grpc/codegen/client/tower_h2/trait.Body.html\" title=\"trait tower_grpc::codegen::client::tower_h2::Body\">Body</a> for <a class=\"struct\" href=\"tower_grpc/struct.BoxBody.html\" title=\"struct tower_grpc::BoxBody\">BoxBody</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://docs.rs/bytes/0.4.11/bytes/buf/into_buf/trait.IntoBuf.html\" title=\"trait bytes::buf::into_buf::IntoBuf\">IntoBuf</a> + 'static,&nbsp;</span>",synthetic:false,types:["tower_grpc::body::BoxBody"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"tower_grpc/codegen/client/tower_h2/trait.Body.html\" title=\"trait tower_grpc::codegen::client::tower_h2::Body\">Body</a> for <a class=\"struct\" href=\"tower_grpc/struct.Encode.html\" title=\"struct tower_grpc::Encode\">Encode</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"tower_grpc/codegen/server/futures/trait.Stream.html\" title=\"trait tower_grpc::codegen::server::futures::Stream\">Stream</a>&lt;Error = <a class=\"enum\" href=\"tower_grpc/enum.Error.html\" title=\"enum tower_grpc::Error\">Error</a>&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;T::<a class=\"type\" href=\"tower_grpc/codegen/server/futures/trait.Stream.html#associatedtype.Item\" title=\"type tower_grpc::codegen::server::futures::Stream::Item\">Item</a>: <a class=\"trait\" href=\"https://docs.rs/prost/0.4.0/prost/message/trait.Message.html\" title=\"trait prost::message::Message\">Message</a>,&nbsp;</span>",synthetic:false,types:["tower_grpc::codec::Encode"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
